# Generated by Django 2.0.6 on 2018-06-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180606_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('qtd_topicos', models.IntegerField()),
                ('topico_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Topico')),
            ],
        ),
    ]
