# Generated by Django 2.0.6 on 2018-06-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180603_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='resposta',
            old_name='resposta_texto',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='topico',
            old_name='topico_texto',
            new_name='texto',
        ),
    ]
